name: Linting

# This action works with pull requests and pushes
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      # Prettier Action: https://github.com/marketplace/actions/prettier-action
      # Prettier config: https://prettier.io/docs/en/configuration.html
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          prettier_options: "*.{jsonc,json,js}"
