name: Validate JSONC

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install jsonc-parser

      - name: Validate JSONC files
        run: |
          for file in *.jsonc; do
            echo "Validating $file"
            npx jsonc-parser parse $file
          done
