name: Validate JSONC

on: [push, pull_request]

jobs:
  validate-jsonc:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install jsonc-parser ajv

      - name: Validate JSONC files
        run: |
          for file in *.jsonc; do
            echo "Validating $file"
            node validate-jsonc.js $file
          done
